// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'flag': string;
  'helpText': string;
  'label': string;
  'legend': string;
  'length': string;
  'limit': string;
  'namingLengths': string;
  'over': string;
  'series': string;
  'table': string;
}
export const cssExports: CssExports;
export default cssExports;
