// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badge': string;
  'edition': string;
  'editions': string;
}
export const cssExports: CssExports;
export default cssExports;
