// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'customFormatTooltip': string;
  'label': string;
  'languages': string;
  'multiple': string;
  'quality': string;
  'relativePath': string;
  'reprocessing': string;
}
export const cssExports: CssExports;
export default cssExports;
