// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chip': string;
  'codes': string;
  'flag': string;
  'flags': string;
  'group': string;
  'icon': string;
  'spaced': string;
  'subtitles': string;
}
export const cssExports: CssExports;
export default cssExports;
